export { default as defaultWindow } from './functions/default-window'
export { default as delay } from './functions/delay'
export { default as file } from './functions/file'
export { default as imageSize } from './functions/image-size'
export { default as inRange } from './functions/in-range'
export { default as loader } from './functions/loader'
export { default as removeHtmlTag } from './functions/remove-html-tag'
export { default as renderTo } from './functions/render-to'
export { default as rndColor } from './functions/rnd-color'
export { default as storage } from './functions/storage'
export { default as tree } from './functions/tree'
export * as changeCase from 'change-case'
