export { default as delay } from './functions/delay'
export { default as removeHtmlTag } from './functions/remove-html-tag'
export { default as rndColor } from './functions/rnd-color'
export { default as storage } from './functions/storage'
export { default as tree } from './functions/tree'
