/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElText: typeof import('element-plus/es')['ElText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VcAwesomeIcon: typeof import('@wfrog/vc-ui/es/components/awesome-icon')['default']
    VcBackbottom: typeof import('@wfrog/vc-ui/es/components/backbottom')['default']
    VcButton: typeof import('@wfrog/vc-ui/es/components/button')['default']
    VcChatContainer: typeof import('@wfrog/vc-ui/es/components/chat-container')['default']
    VcChoice: typeof import('@wfrog/vc-ui/es/components/choice')['default']
    VcChoiceBoolean: typeof import('@wfrog/vc-ui/es/components/choice-boolean')['default']
    VcConfigProvider: typeof import('@wfrog/vc-ui/es/components/config-provider')['default']
    VcCropper: typeof import('@wfrog/vc-ui/es/components/cropper')['default']
    VcCurrency: typeof import('@wfrog/vc-ui/es/components/currency')['default']
    VcDaterangePicker: typeof import('@wfrog/vc-ui/es/components/daterange-picker')['default']
    VcDialog: typeof import('@wfrog/vc-ui/es/components/dialog')['default']
    VcDialogCameraUpload: typeof import('@wfrog/vc-ui/es/components/dialog-camera-upload')['default']
    VcDialogMapPoint: typeof import('@wfrog/vc-ui/es/components/dialog-map-point')['default']
    VcDialogUploadImages: typeof import('@wfrog/vc-ui/es/components/dialog-upload-images')['default']
    VcDrawer: typeof import('@wfrog/vc-ui/es/components/drawer')['default']
    VcEasyPagination: typeof import('@wfrog/vc-ui/es/components/easy-pagination')['default']
    VcElIcon: typeof import('@wfrog/vc-ui/es/components/el-icon')['default']
    VcFlag: typeof import('@wfrog/vc-ui/es/components/flag')['default']
    VcIcon: typeof import('@wfrog/vc-ui/es/components/icon')['default']
    VcImage: typeof import('@wfrog/vc-ui/es/components/image')['default']
    VcInput: typeof import('@wfrog/vc-ui/es/components/input')['default']
    VcInputNumber: typeof import('@wfrog/vc-ui/es/components/input-number')['default']
    VcPcaPicker: typeof import('@wfrog/vc-ui/es/components/pca-picker')['default']
    VcQrCode: typeof import('@wfrog/vc-ui/es/components/qr-code')['default']
    VcScreenfull: typeof import('@wfrog/vc-ui/es/components/screenfull')['default']
    VcSelect: typeof import('@wfrog/vc-ui/es/components/select')['default']
    VcSinglePlayer: typeof import('@wfrog/vc-ui/es/components/single-player')['default']
    VcSvgIcon: typeof import('@wfrog/vc-ui/es/components/svg-icon')['default']
    VcSwitch: typeof import('@wfrog/vc-ui/es/components/switch')['default']
    VcSyncScrollContainer: typeof import('@wfrog/vc-ui/es/components/sync-scroll-container')['default']
    VcTags: typeof import('@wfrog/vc-ui/es/components/tags')['default']
    VcTextEllipsis: typeof import('@wfrog/vc-ui/es/components/text-ellipsis')['default']
    VcThousandInput: typeof import('@wfrog/vc-ui/es/components/thousand-input')['default']
    VcTinymce: typeof import('@wfrog/vc-ui/es/components/tinymce')['default']
    VcTreePicker: typeof import('@wfrog/vc-ui/es/components/tree-picker')['default']
    VcUploadFile: typeof import('@wfrog/vc-ui/es/components/upload-file')['default']
  }
}
