export const componentsData = [
    {
        text: '全局配置',
        items: [
            { text: 'config-provider' },
            { text: 'dark-switcher' },
            { text: 'color-switcher' },
        ],
    },
    {
        text: '布局组件',
        items: [
            { text: 'explorer' },
            { text: 'scrollbar' },
            { text: 'splitter' },
            { text: 'sync-scroll-container' },
        ],
    },
    {
        text: '表单组件',
        items: [
            { text: 'choice' },
            { text: 'choice-boolean' },
            { text: 'currency' },
            { text: 'daterange-picker' },
            { text: 'dialog-map-point' },
            { text: 'dialog-upload-images' },
            { text: 'icon-picker' },
            { text: 'input' },
            { text: 'input-number' },
            { text: 'pca-picker' },
            { text: 'select' },
            { text: 'switch' },
            { text: 'tags' },
            { text: 'thousand-input' },
            { text: 'tinymce' },
            { text: 'tree-picker' },
        ],
    },
    {
        text: '展示组件',
        items: [
            { text: 'backbottom' },
            { text: 'chat-container' },
            { text: 'cropper' },
            { text: 'dialog' },
            { text: 'dialog-camera-upload' },
            { text: 'drag-verify' },
            { text: 'drawer' },
            { text: 'easy-pagination' },
            { text: 'awesome-icon' },
            { text: 'el-icon' },
            { text: 'iconify-icon' },
            { text: 'svg-icon' },
            { text: 'icon' },
            { text: 'button' },
            { text: 'flag' },
            { text: 'image' },
            { text: 'qr-code' },
            { text: 'screenfull' },
            { text: 'single-player' },
            { text: 'text-ellipsis' },
            { text: 'upload-file' },
        ],
    },
]
